### ISSUE TITLE
Upstream tracker

### ISSUE THREAD

**Issue by kamikazechaser** [grassrootseconomics/w3-celo-patch#6]
- [ ] https://github.com/lmittmann/w3/commit/0684f70fe9f4a9294479732e72e2e5c1497d3f7f (w3types: added Message.UnmarshalJSON)
- [ ] https://github.com/lmittmann/w3/commit/61f4b69f5cab2f04098c255390fc8ea2bc7dadad (internal/abi: Improve ABI Parser)
- [ ] https://github.com/lmittmann/w3/commit/4cd6ce8ed47bdee7373e8988e2884a900566ae26 (Fix handling of indexed-fields in event decoding)
- [ ] https://github.com/lmittmann/w3/commit/8f1a2c1cde8310b8ada7bb7f69aa312370d484b8 (Added goreleaser config and action)
